### ISSUE TITLE
Failed to mount component: template or render function not defined.  found in  ---> <Calendar>

### ISSUE THREAD

**Issue by claudeberube** [ExCluSiv3/Vue-Bootstrap-Calendar#2]
I was able to configure the EazyServer/Vue-Bootstrap-Calendar.  But can't find a solution for this one.
Would like to fork your solution in order to add custem behaviour to events.  @eventItemClicked="subscribe"

[main.txt](https://github.com/ExCluSiv3/Vue-Bootstrap-Calendar/files/1650463/main.txt)

[schedule.txt](https://github.com/ExCluSiv3/Vue-Bootstrap-Calendar/files/1650464/schedule.txt)

Thanks,

**Comment by claudeberube** [comment]
Related to https://github.com/EazyServer/Vue-Bootstrap-Calendar/commit/5e268761b5821d168a96b7442eb6794d62f2b757

**Comment by ticlaudeberube** [comment]
Ready to close
